# Generated by Django 4.2.2 on 2023-06-08 04:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_cliente_pedidos_pedidositem_producto_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cliente',
            new_name='costumer',
        ),
        migrations.RenameModel(
            old_name='pedidos',
            new_name='order',
        ),
        migrations.RenameModel(
            old_name='pedidosItem',
            new_name='orderItem',
        ),
        migrations.RenameModel(
            old_name='producto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='costomer',
        ),
    ]
