# Generated by Django 4.2.2 on 2023-06-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_cliente_costumer_rename_pedidos_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pedidos',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='products',
        ),
    ]
