# Generated by Django 4.2.2 on 2023-06-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='costomer',
        ),
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.costumer'),
        ),
    ]
