# Generated by Django 4.2.2 on 2023-06-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_costomer_order_costumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='costumer',
        ),
    ]
