# Generated by Django 4.2.2 on 2023-06-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_customer_shippingaddress_costumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orders',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='orders',
            new_name='order',
        ),
    ]
